### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by fxckinsa1int** [secretum-inc/sashay#6]
![Снимок экрана (379)](https://user-images.githubusercontent.com/100631012/156061468-8f9fe906-1aa5-483c-afe4-b40e1e1db154.png)

**Comment by fxckinsa1int** [comment]
what should i do here. I got this error, but i dont havr any idea how to solve this

**Comment by gerrishons** [comment]
Hello, the bug was fixed, reclone the repo and follow the prompts
